---

version: '3.9'

services:
  app:
    image: wayofdev/php-dev:8.1-fpm-alpine-latest
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: on-failure
    networks:
      - default
    depends_on:
      - database
    links:
      - database
    external_links:
      - "rabbitmq.${PROJECT_SERVICES_NAMESPACE}.alias:rabbitmq"
    environment:
      APP_NAME: ${APP_NAME}
      FAKETIME: "+2h"
    volumes:
      - ./app:/app:rw,cached
      - ./.env:/app/.env
      - ~/.composer:/.composer

  web:
    image: wayofdev/nginx:k8s-alpine-latest
    container_name: ${COMPOSE_PROJECT_NAME}-web
    restart: on-failure
    networks:
      - default
      - shared
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./app:/app:rw,cached
      - ./.env:/app/.env
      - ./certs:/etc/nginx/ssl
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-${COMPOSE_PROJECT_NAME}-secure.rule=Host(`api.${COMPOSE_PROJECT_NAME}.docker`)
      - traefik.http.routers.api-${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure
      - traefik.http.routers.api-${COMPOSE_PROJECT_NAME}-secure.tls=true
      - traefik.http.services.api-${COMPOSE_PROJECT_NAME}-secure.loadbalancer.server.port=8443
      - traefik.http.services.api-${COMPOSE_PROJECT_NAME}-secure.loadbalancer.server.scheme=https

  database:
    image: wayofdev/postgres:15-alpine-latest
    container_name: ${COMPOSE_PROJECT_NAME}-database
    restart: on-failure
    networks:
      - default
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database-data:/var/lib/postgresql/data:cached

volumes:
  database-data:
    name: ${COMPOSE_PROJECT_NAME}-database-data

networks:
  shared:
    external: true
    name: network.${SHARED_SERVICES_NAMESPACE}
  default:
    name: project.${COMPOSE_PROJECT_NAME}
...
