---

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - develop

name: 📦 Deploy to server

defaults:
  run:
    working-directory: app

jobs:
  integration:
    needs:
      - integration
      - shellcheck
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: true

    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v3

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, fileinfo, xdebug
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: 🛠️ Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: ♻️ Restore cached backend dependencies
        id: cached-composer-dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: 📥 Install backend dependencies
        if: steps.cached-composer-dependencies.outputs.cache-hit != 'true'
        run: composer install

      - name: 🛠️ Prepare environment
        run: |
          cd ../ && make env && cd app
          cp ../.env .env
          mkdir -p ./.build/php-cs-fixer
          mkdir -p ./.build/phpstan
          mkdir -p ./.build/phpunit
        env:
          APP_NAME: laravel
          SHARED_SERVICES_NAMESPACE: ss
          PROJECT_SERVICES_NAMESPACE: wod
          COMPOSE_PROJECT_NAME: laravel-starter-tpl

      - name: 📤 Deploy ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }} environment
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          dep: deploy ${{ github.ref == 'refs/heads/master' && 'prod' || 'staging' }}
        env:
          DEPLOYER_STAGING_SLACK_WEBHOOK: ${{ secrets.DEPLOYER_STAGING_SLACK_WEBHOOK }}
          DEPLOYER_STAGING_REMOTE_USER: ${{ secrets.DEPLOYER_STAGING_REMOTE_USER }}
          DEPLOYER_STAGING_HOST: "staging.laravel-starter-tpl.wayof.dev"
          DEPLOYER_STAGING_BRANCH: "develop"
          DEPLOYER_PROD_SLACK_WEBHOOK: ${{ secrets.DEPLOYER_PROD_SLACK_WEBHOOK }}
          DEPLOYER_PROD_REMOTE_USER: ${{ secrets.DEPLOYER_PROD_REMOTE_USER }}
          DEPLOYER_PROD_HOST: "prod.laravel-starter-tpl.wayof.dev"
          DEPLOYER_PROD_BRANCH: "master"
          DEPLOYER_SENTRY_TOKEN: ${{ secrets.DEPLOYER_SENTRY_TOKEN }}
          DEPLOYER_SENTRY_ORG: "wayofdev"
          DEPLOYER_SENTRY_PROJECT: "laravel-starter-tpl"
          DEPLOYER_SENTRY_SERVER: "https://wayofdev.sentry.io"
